# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/myBlock/myBlock.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myBlock || ORIG_REF_NAME==myBlock} -quiet] -quiet

# IP: bd/myBlock/ip/myBlock_axi_dma_0_0/myBlock_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myBlock_axi_dma_0_0 || ORIG_REF_NAME==myBlock_axi_dma_0_0} -quiet] -quiet

# IP: bd/myBlock/ip/myBlock_axi_smc_0/myBlock_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myBlock_axi_smc_0 || ORIG_REF_NAME==myBlock_axi_smc_0} -quiet] -quiet

# IP: bd/myBlock/ip/myBlock_processing_system7_0_0/myBlock_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myBlock_processing_system7_0_0 || ORIG_REF_NAME==myBlock_processing_system7_0_0} -quiet] -quiet

# IP: bd/myBlock/ip/myBlock_xbar_0/myBlock_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myBlock_xbar_0 || ORIG_REF_NAME==myBlock_xbar_0} -quiet] -quiet

# IP: bd/myBlock/ip/myBlock_auto_pc_0/myBlock_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myBlock_auto_pc_0 || ORIG_REF_NAME==myBlock_auto_pc_0} -quiet] -quiet

# IP: bd/myBlock/ip/myBlock_ps7_0_axi_periph_0/myBlock_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myBlock_ps7_0_axi_periph_0 || ORIG_REF_NAME==myBlock_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/myBlock/ip/myBlock_rst_ps7_0_100M_0/myBlock_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myBlock_rst_ps7_0_100M_0 || ORIG_REF_NAME==myBlock_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/myBlock/ip/myBlock_xlconcat_0_0/myBlock_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myBlock_xlconcat_0_0 || ORIG_REF_NAME==myBlock_xlconcat_0_0} -quiet] -quiet

# IP: bd/myBlock/ip/myBlock_zyNet_0_0/myBlock_zyNet_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==myBlock_zyNet_0_0 || ORIG_REF_NAME==myBlock_zyNet_0_0} -quiet] -quiet

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/myBlock_ooc.xdc
