# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.srcs/sources_1/bd/myBlock/ip/myBlock_processing_system7_0_0/myBlock_processing_system7_0_0.xci
# IP: The module: 'myBlock_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_processing_system7_0_0/myBlock_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'myBlock_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.srcs/sources_1/bd/myBlock/ip/myBlock_processing_system7_0_0/myBlock_processing_system7_0_0.xci
# IP: The module: 'myBlock_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_processing_system7_0_0/myBlock_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'myBlock_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
