# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.srcs/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/myBlock_axi_smc_0.xci
# IP: The module: 'myBlock_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/bd_398e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_0/bd_398e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_1/bd_398e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_2/bd_398e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_3/bd_398e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_4/bd_398e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_5/bd_398e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_6/bd_398e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_7/bd_398e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_8/bd_398e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_9/bd_398e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_1/bd_398e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_1/bd_398e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_5/bd_398e_s00a2s_0_ooc.xdc

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_6/bd_398e_sarn_0_ooc.xdc

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_7/bd_398e_srn_0_ooc.xdc

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_8/bd_398e_m00s2a_0_ooc.xdc

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myBlock_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.srcs/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/myBlock_axi_smc_0.xci
# IP: The module: 'myBlock_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/bd_398e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_0/bd_398e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_1/bd_398e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_2/bd_398e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_3/bd_398e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_4/bd_398e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_5/bd_398e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_6/bd_398e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_7/bd_398e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_8/bd_398e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_9/bd_398e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_1/bd_398e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_1/bd_398e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_5/bd_398e_s00a2s_0_ooc.xdc

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_6/bd_398e_sarn_0_ooc.xdc

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_7/bd_398e_srn_0_ooc.xdc

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/bd_0/ip/ip_8/bd_398e_m00s2a_0_ooc.xdc

# XDC: e:/MTP2/neuralNetwork-master/Tut-8/NN-FPGA/NN-FPGA.gen/sources_1/bd/myBlock/ip/myBlock_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myBlock_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
